#name = "claude-code-proxy"
name = "claude-proxy"
main = "src/index.ts"
compatibility_date = "2024-03-20"

[vars]
HAIKU_MODEL_NAME= "@cf/qwen/qwen1.5-7b-chat-awq"
HAIKU_BASE_URL= "https://claude-code-proxy.hacolby.workers.dev"
HAIKU_API_KEY= "sk-**"

[observability.logs]
enabled = true
